ProjectSkripsi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

account/urls.py
from django.urls import path, include
from account import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('', include('django.contrib.auth.urls'))
]

home/urls.py
from django.urls import path, include
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home_view'),
    path('<int:pk>/', views.DataDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('create/', views.create, name='create'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

login/urls.py
from django.urls import path, include
from login import views

app_name = 'login'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', include('django.contrib.auth.urls'))
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=100, blank=True)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

home/models.py
from django.db import models


class Data(models.Model):
    no = models.CharField("No", max_length=50, blank=True, null=True)
    ppm_ch4 = models.CharField("ppm CH4", max_length=50, blank=True, null=True)
    ppm_c2h4 = models.CharField("ppm C2H4", max_length=50, blank=True, null=True)
    ppm_c2h2 = models.CharField("ppm C2H2", max_length=50, blank=True, null=True)
    persen_ch4 = models.CharField("%CH4", max_length=50, blank=True, null=True)
    persen_c2h4 = models.CharField("%C2H4", max_length=50, blank=True, null=True)
    persen_c2h2 = models.CharField("%C2H2", max_length=50, blank=True, null=True)
    fault = models.CharField("Fault", max_length=50, blank=True, null=True)
    created_at = models.DateTimeField("Created At", auto_now_add=True)

    def __str__(self):
        return self.no

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=50,
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(max_length=30,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=150,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    password1 = forms.CharField(max_length=30,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(max_length=30,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirmation'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=20,
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(max_length=20,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'password')

home/forms.py
from django import forms
from .models import Data


class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = "__all__"

account/views.py
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, LoginForm
from django.shortcuts import render, redirect
from django.contrib import messages
import logging


logger = logging.getLogger(__name__)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)

            logger.error(user)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home:home_view')
            else:
                messages.error(request, 'username or password incorrect')
                return redirect('login_view')

    form = LoginForm()
    return render(request, 'login.html', {'form': form})


def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.username = form.cleaned_data.get('username')
            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('home:home_view')

    form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Data
from .forms import DataForm
from django.views.generic import ListView, DetailView


class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'data_list'

    def get_queryset(self):
        return Data.objects.all()


class DataDetailView(DetailView):
    model = Data
    template_name = 'data-detail.html'


def create(request):
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:home_view')
    form = DataForm()

    return render(request, 'create.html', {'form': form})


def edit(request, pk, template_name='edit.html'):
    contact = get_object_or_404(Data, pk=pk)
    form = DataForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('home:home_view')
    return render(request, template_name, {'form': form})


def delete(request, pk, template_name='confirm_delete.html'):
    contact = get_object_or_404(Data, pk=pk)
    if request.method == 'POST':
        contact.delete()
        return redirect('home:home_view')
    return render(request, template_name, {'object': contact})

account/templates/login.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <!-- Custom Theme files -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //web font -->

</head>
<body>
    <div class="login-page">
        <div class="form">
            <form class="login-form" method="post">
                <!--<input type="text" placeholder="username"/>
                <input type="password" placeholder="password"/>-->

                {% csrf_token %}

                {% for field in form %}

                    {{ field }}

                    {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}

                {% endfor %}

                {% for message in messages %}
                    <div class="alert alert-danger" role="alert">

                        {{ message }}

                    </div>
                {% endfor %}

                <button type="submit">login</button>
                <p class="message">Not registered? <a href="{% url 'account:signup_view' %}">Create an account</a></p>
            </form>
        </div>
    </div>
</body>
</html>

account/templates/signup.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
	<title>Register</title>
	<!-- Custom Theme files -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
	<div class="login-page">
        <div class="form">
            <form class="register-form" method="post">
                {% csrf_token %}
                <!--<input type="text" placeholder="Username"/>
                <input type="password" placeholder="Password"/>
                <input type="text" placeholder="Password Confirmation"/>-->

                {% for field in form %}

                    {{ field }}

                    {% if field.help_text %}
                        <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}

                {% endfor %}

                <button type="submit">submit</button>
                <p class="message">Already registered? <a href="{% url 'account:login_view' %}">Log In</a></p>
            </form>
        </div>
    </div>
</body>
</html>

home/templates/base.html
<!DOCTYPE html>
<html>
  <head>
   <title>Data Latih</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  </head>
  <body>
  {% block content %}
  {% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </body>
</html>

home/templates/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row"></div>
    <br />
    <div class="row">
        <div class="col-md-2 col-xs-2 col-sm-2"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <form method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="alert alert-warning">
                        Are you sure you want to delete {{ object }}?
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

home/templates/create.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html>

<head>
    <title>Posts</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style type="text/css">

    </style>

</head>

<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-1 col-xs-1 col-sm-1"></div>

            <div class="col-md-10 col-xs-10 col-sm-10 ">
                <br />
                <h6 style="text-align:center;">
                    <font color="red">DATA LATIH</font>
                </h6>
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1">
            </div>
        </div>
        <div class="row">
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
            <div class="col-md-10 col-xs-10 col-sm-10">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {% render_field field class="form-control" %}
                        {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">SIMPAN</button>
                </form>
                <br>
            </div>
            <div class="col-md-1 col-xs-1 col-sm-1"></div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

home/templates/data-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul class="list-group">
        <li class="list-group-item ">
            <a>No </a> : <a> {{ data.no }} </a>
        </li>
        <li class="list-group-item ">
            <a>ppm CH4 </a> : <a> {{ data.ppm_ch4 }} </a>
        </li>
        <li class="list-group-item ">
            <a>ppm C2H4 </a> : <a> {{ data.ppm_c2h4 }} </a>
        </li>
        <li class="list-group-item ">
            <a>ppm C2H2 </a> : <a> {{ data.ppm_c2h2 }} </a>
        </li>
        <li class="list-group-item ">
            <a>%CH4 </a> : <a> {{ data.persen_ch4 }} </a>
        </li>
        <li class="list-group-item ">
            <a>%C2H4 </a> : <a> {{ data.persen_c2h4 }} </a>
        </li>
        <li class="list-group-item ">
            <a>%C2H2 </a> : <a> {{ data.persen_c2h2 }} </a>
        </li>
        <li class="list-group-item ">
            <a>Fault </a> : <a> {{ data.fault }} </a>
        </li>
    </ul>
</body>
</html>

home/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

home/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>

</body>
</html>

home/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-10 col-xs-10 col-sm-10">
            <h2 class="round3" style="text-align:center;">DATA LATIH</h2>
        </div>
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    <div class="row">
        <div class="col-md-1 col-xs-10 col-sm-10"></div>
        <div class="col-md-2 col-xs-1 col-sm-1">
            <br />
            <a href="{% url 'home:create' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </a>
        </div>
    </div>
    <br />
    {% for data in data_list %}
    <div class="row">
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
        <div class="col-md-4 col-xs-7 col-sm-7">
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{% url 'home:detail' data.pk %}"> {{ data.no }} </a> <span class="badge"></span>
                </li>
            </ul>
        </div>
        <!--<div class="col-md-1 col-xs-1 col-sm-1">
            <a href="{% url 'home:detail' data.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-open"></span>
                </button>
            </a>
        </div>
        <div class="col-md-1">
            <a href="{% url 'home:edit' data.pk %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil"></span>
                </button>
            </a>
        </div>
        <div class="col-md-1">
            <a href="{% url 'home:delete' data.pk %}">
                <button type="button" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </a>
        </div>-->
        <div class="col-md-1 col-xs-1 col-sm-1"></div>
    </div>
    {% endfor %}
</div>
{% endblock %}